/**
 * ISO 3166-1 countries (alpha-2, Ukrainian, English) — the SAME list the
 * frontend country combobox uses (frontend/lib/shipmentOptions.ts), so values the
 * backend writes into origin_country / destination_country are ones the UI can
 * show. The workspace stores the Ukrainian name.
 */
export const COUNTRIES: readonly (readonly [code: string, uk: string, en: string])[] = [
  ["AU", "Австралія", "Australia"],
  ["AT", "Австрія", "Austria"],
  ["AZ", "Азербайджан", "Azerbaijan"],
  ["AL", "Албанія", "Albania"],
  ["DZ", "Алжир", "Algeria"],
  ["AO", "Ангола", "Angola"],
  ["AD", "Андорра", "Andorra"],
  ["AR", "Аргентина", "Argentina"],
  ["AM", "Вірменія", "Armenia"],
  ["AF", "Афганістан", "Afghanistan"],
  ["BS", "Багамські Острови", "Bahamas"],
  ["BD", "Бангладеш", "Bangladesh"],
  ["BB", "Барбадос", "Barbados"],
  ["BH", "Бахрейн", "Bahrain"],
  ["BY", "Білорусь", "Belarus"],
  ["BZ", "Беліз", "Belize"],
  ["BE", "Бельгія", "Belgium"],
  ["BJ", "Бенін", "Benin"],
  ["BG", "Болгарія", "Bulgaria"],
  ["BO", "Болівія", "Bolivia"],
  ["BA", "Боснія і Герцеговина", "Bosnia and Herzegovina"],
  ["BW", "Ботсвана", "Botswana"],
  ["BR", "Бразилія", "Brazil"],
  ["BN", "Бруней", "Brunei"],
  ["BF", "Буркіна-Фасо", "Burkina Faso"],
  ["BI", "Бурунді", "Burundi"],
  ["BT", "Бутан", "Bhutan"],
  ["VU", "Вануату", "Vanuatu"],
  ["GB", "Велика Британія", "United Kingdom"],
  ["VE", "Венесуела", "Venezuela"],
  ["VN", "В'єтнам", "Vietnam"],
  ["GA", "Габон", "Gabon"],
  ["HT", "Гаїті", "Haiti"],
  ["GY", "Гаяна", "Guyana"],
  ["GM", "Гамбія", "Gambia"],
  ["GH", "Гана", "Ghana"],
  ["GT", "Гватемала", "Guatemala"],
  ["GN", "Гвінея", "Guinea"],
  ["GW", "Гвінея-Бісау", "Guinea-Bissau"],
  ["DE", "Німеччина", "Germany"],
  ["HN", "Гондурас", "Honduras"],
  ["GD", "Гренада", "Grenada"],
  ["GR", "Греція", "Greece"],
  ["GE", "Грузія", "Georgia"],
  ["DK", "Данія", "Denmark"],
  ["DJ", "Джибуті", "Djibouti"],
  ["DM", "Домініка", "Dominica"],
  ["DO", "Домініканська Республіка", "Dominican Republic"],
  ["EG", "Єгипет", "Egypt"],
  ["EC", "Еквадор", "Ecuador"],
  ["GQ", "Екваторіальна Гвінея", "Equatorial Guinea"],
  ["ER", "Еритрея", "Eritrea"],
  ["SZ", "Есватіні", "Eswatini"],
  ["EE", "Естонія", "Estonia"],
  ["ET", "Ефіопія", "Ethiopia"],
  ["YE", "Ємен", "Yemen"],
  ["ZM", "Замбія", "Zambia"],
  ["ZW", "Зімбабве", "Zimbabwe"],
  ["IL", "Ізраїль", "Israel"],
  ["IN", "Індія", "India"],
  ["ID", "Індонезія", "Indonesia"],
  ["IQ", "Ірак", "Iraq"],
  ["IR", "Іран", "Iran"],
  ["IE", "Ірландія", "Ireland"],
  ["IS", "Ісландія", "Iceland"],
  ["ES", "Іспанія", "Spain"],
  ["IT", "Італія", "Italy"],
  ["JO", "Йорданія", "Jordan"],
  ["CV", "Кабо-Верде", "Cape Verde"],
  ["KZ", "Казахстан", "Kazakhstan"],
  ["KH", "Камбоджа", "Cambodia"],
  ["CM", "Камерун", "Cameroon"],
  ["CA", "Канада", "Canada"],
  ["QA", "Катар", "Qatar"],
  ["KE", "Кенія", "Kenya"],
  ["KG", "Киргизстан", "Kyrgyzstan"],
  ["CN", "Китай", "China"],
  ["CY", "Кіпр", "Cyprus"],
  ["KI", "Кірибаті", "Kiribati"],
  ["CO", "Колумбія", "Colombia"],
  ["KM", "Коморські Острови", "Comoros"],
  ["CG", "Конго", "Congo"],
  ["CD", "Демократична Республіка Конго", "DR Congo"],
  ["CR", "Коста-Рика", "Costa Rica"],
  ["CI", "Кот-д'Івуар", "Côte d'Ivoire"],
  ["CU", "Куба", "Cuba"],
  ["KW", "Кувейт", "Kuwait"],
  ["LA", "Лаос", "Laos"],
  ["LV", "Латвія", "Latvia"],
  ["LS", "Лесото", "Lesotho"],
  ["LT", "Литва", "Lithuania"],
  ["LR", "Ліберія", "Liberia"],
  ["LB", "Ліван", "Lebanon"],
  ["LY", "Лівія", "Libya"],
  ["LI", "Ліхтенштейн", "Liechtenstein"],
  ["LU", "Люксембург", "Luxembourg"],
  ["MU", "Маврикій", "Mauritius"],
  ["MR", "Мавританія", "Mauritania"],
  ["MG", "Мадагаскар", "Madagascar"],
  ["MK", "Північна Македонія", "North Macedonia"],
  ["MW", "Малаві", "Malawi"],
  ["MY", "Малайзія", "Malaysia"],
  ["ML", "Малі", "Mali"],
  ["MV", "Мальдіви", "Maldives"],
  ["MT", "Мальта", "Malta"],
  ["MA", "Марокко", "Morocco"],
  ["MH", "Маршаллові Острови", "Marshall Islands"],
  ["MX", "Мексика", "Mexico"],
  ["FM", "Мікронезія", "Micronesia"],
  ["MZ", "Мозамбік", "Mozambique"],
  ["MD", "Молдова", "Moldova"],
  ["MC", "Монако", "Monaco"],
  ["MN", "Монголія", "Mongolia"],
  ["MM", "М'янма", "Myanmar"],
  ["NA", "Намібія", "Namibia"],
  ["NR", "Науру", "Nauru"],
  ["NP", "Непал", "Nepal"],
  ["NE", "Нігер", "Niger"],
  ["NG", "Нігерія", "Nigeria"],
  ["NL", "Нідерланди", "Netherlands"],
  ["NI", "Нікарагуа", "Nicaragua"],
  ["NZ", "Нова Зеландія", "New Zealand"],
  ["NO", "Норвегія", "Norway"],
  ["AE", "Об'єднані Арабські Емірати", "United Arab Emirates"],
  ["OM", "Оман", "Oman"],
  ["PK", "Пакистан", "Pakistan"],
  ["PW", "Палау", "Palau"],
  ["PS", "Палестина", "Palestine"],
  ["PA", "Панама", "Panama"],
  ["PG", "Папуа-Нова Гвінея", "Papua New Guinea"],
  ["PY", "Парагвай", "Paraguay"],
  ["PE", "Перу", "Peru"],
  ["ZA", "Південно-Африканська Республіка", "South Africa"],
  ["KR", "Південна Корея", "South Korea"],
  ["SS", "Південний Судан", "South Sudan"],
  ["PL", "Польща", "Poland"],
  ["PT", "Португалія", "Portugal"],
  ["RU", "Росія", "Russia"],
  ["RW", "Руанда", "Rwanda"],
  ["RO", "Румунія", "Romania"],
  ["SV", "Сальвадор", "El Salvador"],
  ["WS", "Самоа", "Samoa"],
  ["SM", "Сан-Марино", "San Marino"],
  ["ST", "Сан-Томе і Принсіпі", "São Tomé and Príncipe"],
  ["SA", "Саудівська Аравія", "Saudi Arabia"],
  ["SC", "Сейшельські Острови", "Seychelles"],
  ["SN", "Сенегал", "Senegal"],
  ["VC", "Сент-Вінсент і Гренадини", "Saint Vincent and the Grenadines"],
  ["KN", "Сент-Кітс і Невіс", "Saint Kitts and Nevis"],
  ["LC", "Сент-Люсія", "Saint Lucia"],
  ["RS", "Сербія", "Serbia"],
  ["SG", "Сінгапур", "Singapore"],
  ["SY", "Сирія", "Syria"],
  ["SK", "Словаччина", "Slovakia"],
  ["SI", "Словенія", "Slovenia"],
  ["SB", "Соломонові Острови", "Solomon Islands"],
  ["SO", "Сомалі", "Somalia"],
  ["SD", "Судан", "Sudan"],
  ["SR", "Суринам", "Suriname"],
  ["US", "Сполучені Штати Америки", "United States"],
  ["SL", "Сьєрра-Леоне", "Sierra Leone"],
  ["TJ", "Таджикистан", "Tajikistan"],
  ["TH", "Таїланд", "Thailand"],
  ["TZ", "Танзанія", "Tanzania"],
  ["TG", "Того", "Togo"],
  ["TO", "Тонга", "Tonga"],
  ["TT", "Тринідад і Тобаго", "Trinidad and Tobago"],
  ["TV", "Тувалу", "Tuvalu"],
  ["TN", "Туніс", "Tunisia"],
  ["TM", "Туркменістан", "Turkmenistan"],
  ["TR", "Туреччина", "Turkey"],
  ["UG", "Уганда", "Uganda"],
  ["HU", "Угорщина", "Hungary"],
  ["UZ", "Узбекистан", "Uzbekistan"],
  ["UA", "Україна", "Ukraine"],
  ["UY", "Уругвай", "Uruguay"],
  ["FJ", "Фіджі", "Fiji"],
  ["PH", "Філіппіни", "Philippines"],
  ["FI", "Фінляндія", "Finland"],
  ["FR", "Франція", "France"],
  ["HR", "Хорватія", "Croatia"],
  ["CF", "Центральноафриканська Республіка", "Central African Republic"],
  ["TD", "Чад", "Chad"],
  ["ME", "Чорногорія", "Montenegro"],
  ["CZ", "Чехія", "Czechia"],
  ["CL", "Чилі", "Chile"],
  ["CH", "Швейцарія", "Switzerland"],
  ["SE", "Швеція", "Sweden"],
  ["LK", "Шрі-Ланка", "Sri Lanka"],
  ["JM", "Ямайка", "Jamaica"],
  ["JP", "Японія", "Japan"],
];

const ALIASES: Record<string, string> = {
  uk: "GB", "great britain": "GB", england: "GB", britain: "GB", "united kingdom of great britain and northern ireland": "GB",
  usa: "US", "united states of america": "US", "u.s.a.": "US",
  "republic of india": "IN", "народна республіка китай": "CN", "prc": "CN", "people's republic of china": "CN",
  "україни": "UA", "украина": "UA", "индия": "IN", "китай": "CN", "германия": "DE", "великобритания": "GB",
  "korea": "KR", "republic of korea": "KR", "turkiye": "TR", "türkiye": "TR", "czech republic": "CZ",
};

const norm = (s: string): string => s.trim().toLowerCase().replace(/[.,]/g, "").replace(/\s+/g, " ");

/**
 * Ukrainian country name for a free-text country read from a document
 * ("India", "Індія/India", "IN", "INDIA (IN)") — null when it can't be resolved.
 */
export function countryToUk(raw: string | null | undefined): string | null {
  if (!raw) return null;
  const parts = raw.split(/[/|(),;]/).map(norm).filter(Boolean);
  for (const p of [norm(raw), ...parts]) {
    const code = ALIASES[p] ?? (p.length === 2 ? p.toUpperCase() : undefined);
    const hit = COUNTRIES.find((c) => (code && c[0] === code) || norm(c[1]) === p || norm(c[2]) === p);
    if (hit) return hit[1];
  }
  return null;
}
