// Static option data for the shipment sidebar: Incoterms® 2020, transport modes
// (with the Incoterm→mode filter), and the ISO 3166-1 country list (uk + en) for
// the searchable country combobox. Values are stored human-readable: the Incoterm
// `code`, the transport `value` slug, and the Ukrainian country name.

export interface Option {
  value: string;
  label: string;
}

export const INCOTERMS_2020: Option[] = [
  { value: "EXW", label: "EXW — Ex Works / Франко-завод" },
  { value: "FCA", label: "FCA — Free Carrier / Франко-перевізник" },
  { value: "FAS", label: "FAS — Free Alongside Ship / Вільно вздовж борту судна" },
  { value: "FOB", label: "FOB — Free On Board / Вільно на борту" },
  { value: "CFR", label: "CFR — Cost and Freight / Вартість і фрахт" },
  { value: "CIF", label: "CIF — Cost, Insurance and Freight / Вартість, страхування, фрахт" },
  { value: "CPT", label: "CPT — Carriage Paid To / Фрахт оплачено до" },
  { value: "CIP", label: "CIP — Carriage and Insurance Paid To / Фрахт і страхування оплачено до" },
  { value: "DAP", label: "DAP — Delivered At Place / Постачання в місці призначення" },
  { value: "DPU", label: "DPU — Delivered at Place Unloaded / Постачання в місці розвантаження" },
  { value: "DDP", label: "DDP — Delivered Duty Paid / Постачання зі сплатою мит" },
];

export const TRANSPORT_MODES: Option[] = [
  { value: "sea", label: "Морський" },
  { value: "air", label: "Авіа" },
  { value: "rail", label: "Залізничний" },
  { value: "road", label: "Автомобільний" },
  { value: "multimodal", label: "Мультимодальний" },
  { value: "inland_waterway", label: "Внутрішні водні шляхи" },
  { value: "pipeline", label: "Трубопровідний" },
  { value: "courier", label: "Кур'єрський/Експрес" },
];

// Incoterms that apply only to sea / inland-waterway transport.
export const SEA_ONLY_INCOTERMS = new Set(["FAS", "FOB", "CFR", "CIF"]);

/** Transport modes valid for the given Incoterm (sea-only terms restrict to water). */
export function transportOptionsFor(incoterm: string): Option[] {
  if (SEA_ONLY_INCOTERMS.has(incoterm)) {
    return TRANSPORT_MODES.filter((m) => m.value === "sea" || m.value === "inland_waterway");
  }
  return TRANSPORT_MODES;
}

export interface Country {
  code: string; // ISO 3166-1 alpha-2
  uk: string;
  en: string;
}

// ISO 3166-1 countries (UN members + common territories), Ukrainian + English.
export const COUNTRIES: Country[] = [
  { code: "AU", uk: "Австралія", en: "Australia" },
  { code: "AT", uk: "Австрія", en: "Austria" },
  { code: "AZ", uk: "Азербайджан", en: "Azerbaijan" },
  { code: "AL", uk: "Албанія", en: "Albania" },
  { code: "DZ", uk: "Алжир", en: "Algeria" },
  { code: "AO", uk: "Ангола", en: "Angola" },
  { code: "AD", uk: "Андорра", en: "Andorra" },
  { code: "AR", uk: "Аргентина", en: "Argentina" },
  { code: "AM", uk: "Вірменія", en: "Armenia" },
  { code: "AF", uk: "Афганістан", en: "Afghanistan" },
  { code: "BS", uk: "Багамські Острови", en: "Bahamas" },
  { code: "BD", uk: "Бангладеш", en: "Bangladesh" },
  { code: "BB", uk: "Барбадос", en: "Barbados" },
  { code: "BH", uk: "Бахрейн", en: "Bahrain" },
  { code: "BY", uk: "Білорусь", en: "Belarus" },
  { code: "BZ", uk: "Беліз", en: "Belize" },
  { code: "BE", uk: "Бельгія", en: "Belgium" },
  { code: "BJ", uk: "Бенін", en: "Benin" },
  { code: "BG", uk: "Болгарія", en: "Bulgaria" },
  { code: "BO", uk: "Болівія", en: "Bolivia" },
  { code: "BA", uk: "Боснія і Герцеговина", en: "Bosnia and Herzegovina" },
  { code: "BW", uk: "Ботсвана", en: "Botswana" },
  { code: "BR", uk: "Бразилія", en: "Brazil" },
  { code: "BN", uk: "Бруней", en: "Brunei" },
  { code: "BF", uk: "Буркіна-Фасо", en: "Burkina Faso" },
  { code: "BI", uk: "Бурунді", en: "Burundi" },
  { code: "BT", uk: "Бутан", en: "Bhutan" },
  { code: "VU", uk: "Вануату", en: "Vanuatu" },
  { code: "GB", uk: "Велика Британія", en: "United Kingdom" },
  { code: "VE", uk: "Венесуела", en: "Venezuela" },
  { code: "VN", uk: "В'єтнам", en: "Vietnam" },
  { code: "GA", uk: "Габон", en: "Gabon" },
  { code: "HT", uk: "Гаїті", en: "Haiti" },
  { code: "GY", uk: "Гаяна", en: "Guyana" },
  { code: "GM", uk: "Гамбія", en: "Gambia" },
  { code: "GH", uk: "Гана", en: "Ghana" },
  { code: "GT", uk: "Гватемала", en: "Guatemala" },
  { code: "GN", uk: "Гвінея", en: "Guinea" },
  { code: "GW", uk: "Гвінея-Бісау", en: "Guinea-Bissau" },
  { code: "DE", uk: "Німеччина", en: "Germany" },
  { code: "HN", uk: "Гондурас", en: "Honduras" },
  { code: "GD", uk: "Гренада", en: "Grenada" },
  { code: "GR", uk: "Греція", en: "Greece" },
  { code: "GE", uk: "Грузія", en: "Georgia" },
  { code: "DK", uk: "Данія", en: "Denmark" },
  { code: "DJ", uk: "Джибуті", en: "Djibouti" },
  { code: "DM", uk: "Домініка", en: "Dominica" },
  { code: "DO", uk: "Домініканська Республіка", en: "Dominican Republic" },
  { code: "EG", uk: "Єгипет", en: "Egypt" },
  { code: "EC", uk: "Еквадор", en: "Ecuador" },
  { code: "GQ", uk: "Екваторіальна Гвінея", en: "Equatorial Guinea" },
  { code: "ER", uk: "Еритрея", en: "Eritrea" },
  { code: "SZ", uk: "Есватіні", en: "Eswatini" },
  { code: "EE", uk: "Естонія", en: "Estonia" },
  { code: "ET", uk: "Ефіопія", en: "Ethiopia" },
  { code: "YE", uk: "Ємен", en: "Yemen" },
  { code: "ZM", uk: "Замбія", en: "Zambia" },
  { code: "ZW", uk: "Зімбабве", en: "Zimbabwe" },
  { code: "IL", uk: "Ізраїль", en: "Israel" },
  { code: "IN", uk: "Індія", en: "India" },
  { code: "ID", uk: "Індонезія", en: "Indonesia" },
  { code: "IQ", uk: "Ірак", en: "Iraq" },
  { code: "IR", uk: "Іран", en: "Iran" },
  { code: "IE", uk: "Ірландія", en: "Ireland" },
  { code: "IS", uk: "Ісландія", en: "Iceland" },
  { code: "ES", uk: "Іспанія", en: "Spain" },
  { code: "IT", uk: "Італія", en: "Italy" },
  { code: "JO", uk: "Йорданія", en: "Jordan" },
  { code: "CV", uk: "Кабо-Верде", en: "Cape Verde" },
  { code: "KZ", uk: "Казахстан", en: "Kazakhstan" },
  { code: "KH", uk: "Камбоджа", en: "Cambodia" },
  { code: "CM", uk: "Камерун", en: "Cameroon" },
  { code: "CA", uk: "Канада", en: "Canada" },
  { code: "QA", uk: "Катар", en: "Qatar" },
  { code: "KE", uk: "Кенія", en: "Kenya" },
  { code: "KG", uk: "Киргизстан", en: "Kyrgyzstan" },
  { code: "CN", uk: "Китай", en: "China" },
  { code: "CY", uk: "Кіпр", en: "Cyprus" },
  { code: "KI", uk: "Кірибаті", en: "Kiribati" },
  { code: "CO", uk: "Колумбія", en: "Colombia" },
  { code: "KM", uk: "Коморські Острови", en: "Comoros" },
  { code: "CG", uk: "Конго", en: "Congo" },
  { code: "CD", uk: "Демократична Республіка Конго", en: "DR Congo" },
  { code: "CR", uk: "Коста-Рика", en: "Costa Rica" },
  { code: "CI", uk: "Кот-д'Івуар", en: "Côte d'Ivoire" },
  { code: "CU", uk: "Куба", en: "Cuba" },
  { code: "KW", uk: "Кувейт", en: "Kuwait" },
  { code: "LA", uk: "Лаос", en: "Laos" },
  { code: "LV", uk: "Латвія", en: "Latvia" },
  { code: "LS", uk: "Лесото", en: "Lesotho" },
  { code: "LT", uk: "Литва", en: "Lithuania" },
  { code: "LR", uk: "Ліберія", en: "Liberia" },
  { code: "LB", uk: "Ліван", en: "Lebanon" },
  { code: "LY", uk: "Лівія", en: "Libya" },
  { code: "LI", uk: "Ліхтенштейн", en: "Liechtenstein" },
  { code: "LU", uk: "Люксембург", en: "Luxembourg" },
  { code: "MU", uk: "Маврикій", en: "Mauritius" },
  { code: "MR", uk: "Мавританія", en: "Mauritania" },
  { code: "MG", uk: "Мадагаскар", en: "Madagascar" },
  { code: "MK", uk: "Північна Македонія", en: "North Macedonia" },
  { code: "MW", uk: "Малаві", en: "Malawi" },
  { code: "MY", uk: "Малайзія", en: "Malaysia" },
  { code: "ML", uk: "Малі", en: "Mali" },
  { code: "MV", uk: "Мальдіви", en: "Maldives" },
  { code: "MT", uk: "Мальта", en: "Malta" },
  { code: "MA", uk: "Марокко", en: "Morocco" },
  { code: "MH", uk: "Маршаллові Острови", en: "Marshall Islands" },
  { code: "MX", uk: "Мексика", en: "Mexico" },
  { code: "FM", uk: "Мікронезія", en: "Micronesia" },
  { code: "MZ", uk: "Мозамбік", en: "Mozambique" },
  { code: "MD", uk: "Молдова", en: "Moldova" },
  { code: "MC", uk: "Монако", en: "Monaco" },
  { code: "MN", uk: "Монголія", en: "Mongolia" },
  { code: "MM", uk: "М'янма", en: "Myanmar" },
  { code: "NA", uk: "Намібія", en: "Namibia" },
  { code: "NR", uk: "Науру", en: "Nauru" },
  { code: "NP", uk: "Непал", en: "Nepal" },
  { code: "NE", uk: "Нігер", en: "Niger" },
  { code: "NG", uk: "Нігерія", en: "Nigeria" },
  { code: "NL", uk: "Нідерланди", en: "Netherlands" },
  { code: "NI", uk: "Нікарагуа", en: "Nicaragua" },
  { code: "NZ", uk: "Нова Зеландія", en: "New Zealand" },
  { code: "NO", uk: "Норвегія", en: "Norway" },
  { code: "AE", uk: "Об'єднані Арабські Емірати", en: "United Arab Emirates" },
  { code: "OM", uk: "Оман", en: "Oman" },
  { code: "PK", uk: "Пакистан", en: "Pakistan" },
  { code: "PW", uk: "Палау", en: "Palau" },
  { code: "PS", uk: "Палестина", en: "Palestine" },
  { code: "PA", uk: "Панама", en: "Panama" },
  { code: "PG", uk: "Папуа-Нова Гвінея", en: "Papua New Guinea" },
  { code: "PY", uk: "Парагвай", en: "Paraguay" },
  { code: "PE", uk: "Перу", en: "Peru" },
  { code: "ZA", uk: "Південно-Африканська Республіка", en: "South Africa" },
  { code: "KR", uk: "Південна Корея", en: "South Korea" },
  { code: "SS", uk: "Південний Судан", en: "South Sudan" },
  { code: "PL", uk: "Польща", en: "Poland" },
  { code: "PT", uk: "Португалія", en: "Portugal" },
  { code: "RU", uk: "Росія", en: "Russia" },
  { code: "RW", uk: "Руанда", en: "Rwanda" },
  { code: "RO", uk: "Румунія", en: "Romania" },
  { code: "SV", uk: "Сальвадор", en: "El Salvador" },
  { code: "WS", uk: "Самоа", en: "Samoa" },
  { code: "SM", uk: "Сан-Марино", en: "San Marino" },
  { code: "ST", uk: "Сан-Томе і Принсіпі", en: "São Tomé and Príncipe" },
  { code: "SA", uk: "Саудівська Аравія", en: "Saudi Arabia" },
  { code: "SC", uk: "Сейшельські Острови", en: "Seychelles" },
  { code: "SN", uk: "Сенегал", en: "Senegal" },
  { code: "VC", uk: "Сент-Вінсент і Гренадини", en: "Saint Vincent and the Grenadines" },
  { code: "KN", uk: "Сент-Кітс і Невіс", en: "Saint Kitts and Nevis" },
  { code: "LC", uk: "Сент-Люсія", en: "Saint Lucia" },
  { code: "RS", uk: "Сербія", en: "Serbia" },
  { code: "SG", uk: "Сінгапур", en: "Singapore" },
  { code: "SY", uk: "Сирія", en: "Syria" },
  { code: "SK", uk: "Словаччина", en: "Slovakia" },
  { code: "SI", uk: "Словенія", en: "Slovenia" },
  { code: "SB", uk: "Соломонові Острови", en: "Solomon Islands" },
  { code: "SO", uk: "Сомалі", en: "Somalia" },
  { code: "SD", uk: "Судан", en: "Sudan" },
  { code: "SR", uk: "Суринам", en: "Suriname" },
  { code: "US", uk: "Сполучені Штати Америки", en: "United States" },
  { code: "SL", uk: "Сьєрра-Леоне", en: "Sierra Leone" },
  { code: "TJ", uk: "Таджикистан", en: "Tajikistan" },
  { code: "TH", uk: "Таїланд", en: "Thailand" },
  { code: "TZ", uk: "Танзанія", en: "Tanzania" },
  { code: "TG", uk: "Того", en: "Togo" },
  { code: "TO", uk: "Тонга", en: "Tonga" },
  { code: "TT", uk: "Тринідад і Тобаго", en: "Trinidad and Tobago" },
  { code: "TV", uk: "Тувалу", en: "Tuvalu" },
  { code: "TN", uk: "Туніс", en: "Tunisia" },
  { code: "TM", uk: "Туркменістан", en: "Turkmenistan" },
  { code: "TR", uk: "Туреччина", en: "Turkey" },
  { code: "UG", uk: "Уганда", en: "Uganda" },
  { code: "HU", uk: "Угорщина", en: "Hungary" },
  { code: "UZ", uk: "Узбекистан", en: "Uzbekistan" },
  { code: "UA", uk: "Україна", en: "Ukraine" },
  { code: "UY", uk: "Уругвай", en: "Uruguay" },
  { code: "FJ", uk: "Фіджі", en: "Fiji" },
  { code: "PH", uk: "Філіппіни", en: "Philippines" },
  { code: "FI", uk: "Фінляндія", en: "Finland" },
  { code: "FR", uk: "Франція", en: "France" },
  { code: "HR", uk: "Хорватія", en: "Croatia" },
  { code: "CF", uk: "Центральноафриканська Республіка", en: "Central African Republic" },
  { code: "TD", uk: "Чад", en: "Chad" },
  { code: "ME", uk: "Чорногорія", en: "Montenegro" },
  { code: "CZ", uk: "Чехія", en: "Czechia" },
  { code: "CL", uk: "Чилі", en: "Chile" },
  { code: "CH", uk: "Швейцарія", en: "Switzerland" },
  { code: "SE", uk: "Швеція", en: "Sweden" },
  { code: "LK", uk: "Шрі-Ланка", en: "Sri Lanka" },
  { code: "JM", uk: "Ямайка", en: "Jamaica" },
  { code: "JP", uk: "Японія", en: "Japan" },
];

/** Case-insensitive prefix/substring match on Ukrainian or English name. */
export function searchCountries(q: string): Country[] {
  const s = q.trim().toLowerCase();
  if (!s) return COUNTRIES;
  return COUNTRIES.filter(
    (c) => c.uk.toLowerCase().includes(s) || c.en.toLowerCase().includes(s),
  );
}
